<?php

return [
    'positions' => [
        'title' => 'Chức vụ',
        'subtitle' => 'Quản trị danh mục chức vụ trong hệ thống',
        'service' => 'hr',
        'resource' => 'positions',
        'legacy_prefix' => 'chucvu',
        'legacy_name' => 'chucvu',
        'permission' => ['view' => 'xem_chucvu', 'create' => 'them_chucvu', 'update' => 'sua_chucvu', 'delete' => 'xoa_chucvu'],
        'read_only' => true,
        'disable_filter' => true,
        'disable_export' => true,
        'hidden_columns' => ['TrangThai'],
        'hide_actions' => true,
        'field_labels' => [
            'MaCV' => 'Mã chức vụ',
            'TenCV' => 'Tên chức vụ',
            'HeSoChucVu' => 'Hệ số chức vụ',
            'PhuCap' => 'Phụ cấp',
            'MoTa' => 'Mô tả',
        ],
    ],
    'assignments' => [
        'title' => 'Phân công',
        'subtitle' => 'Quản trị điều động nhân sự và phân công công việc',
        'service' => 'hr',
        'resource' => 'assignments',
        'legacy_prefix' => 'phancong',
        'legacy_name' => 'phancong',
        'permission' => ['view' => 'xem_phancong', 'create' => 'them_phancong', 'update' => 'sua_phancong', 'delete' => 'xoa_phancong'],
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien',  'value_col' => 'MaNV', 'label_col' => 'HoTen'],
            'MaPB' => ['service' => 'hr', 'table' => 'phongban',  'value_col' => 'MaPB', 'label_col' => 'TenPB'],
            'MaCV' => ['service' => 'hr', 'table' => 'chucvu',    'value_col' => 'MaCV', 'label_col' => 'TenCV'],
        ],
        'field_labels' => [
            'MaQT'          => 'Mã quá trình',
            'MaNV'          => 'Mã nhân viên',
            'MaPB'          => 'Phòng ban',
            'MaCV'          => 'Mã chức vụ',
            'NgayBatDau'    => 'Ngày bắt đầu',
            'NgayKetThuc'   => 'Ngày kết thúc',
            'LyDoThayDoi'   => 'Lý do thay đổi',
            'LoaiDieuChuyen' => 'Loại điều chuyển',
        ],
        'field_value_labels' => [
            'LoaiDieuChuyen' => [
                'Bo nhiem' => 'Bổ nhiệm',
                'Dieu dong' => 'Điều động',
                'Tuyen dung' => 'Tuyển dụng',
                'Thuc tap' => 'Thực tập',
            ],
        ],
    ],
    'insurances' => [
        'title' => 'Bảo hiểm',
        'subtitle' => 'Quản trị bảo hiểm nhân viên trong hệ thống',
        'service' => 'hr',
        'resource' => 'insurances',
        'legacy_prefix' => 'baohiem',
        'legacy_name' => 'baohiem',
        'permission' => ['view' => 'xem_baohiem', 'create' => 'them_baohiem', 'update' => 'sua_baohiem', 'delete' => 'xoa_baohiem'],
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien', 'value_col' => 'MaNV', 'label_col' => 'HoTen'],
        ],
        'field_options' => [
            'LoaiBaoHiem' => ['BHXH', 'BHYT', 'BHTN'],
            'TrangThai'   => ['Đang đóng', 'Đã dừng'],
        ],
        'field_labels' => [
            'MaBH'            => 'Mã bảo hiểm',
            'MaNV'            => 'Nhân viên',
            'SoBHXH'          => 'Số bảo hiểm xã hội',
            'LoaiBaoHiem'     => 'Loại bảo hiểm',
            'NgayThamGia'     => 'Ngày tham gia',
            'MucDong'         => 'Mức đóng',
            'CongTyDong'      => 'Công ty đóng',
            'NhanVienDong'    => 'Nhân viên đóng',
            'TrangThai'       => 'Trạng thái',
            'created_at'      => 'Ngày tạo',
        ],
    ],
    'leave-requests' => [
        'title' => 'Nghỉ phép',
        'subtitle' => 'Quản trị đơn nghỉ phép trong hệ thống',
        'service' => 'hr',
        'resource' => 'leave-requests',
        'legacy_prefix' => 'nghiphep',
        'legacy_name' => 'nghiphep',
        'permission' => ['view' => 'xem_nghiphep', 'create' => 'them_nghiphep', 'update' => 'sua_nghiphep', 'delete' => 'xoa_nghiphep'],
        'auto_fill_ma_nv' => true,
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien', 'value_col' => 'MaNV', 'label_col' => 'HoTen'],
        ],
        'field_labels' => [
            'MaNP'       => 'Mã nghỉ phép',
            'MaNV'       => 'Nhân viên',
            'TuNgay'     => 'Từ ngày',
            'DenNgay'    => 'Đến ngày',
            'SoNgayNghi' => 'Số ngày nghỉ',
            'LyDo'       => 'Lý do',
            'LoaiNghi'   => 'Loại nghỉ',
            'TrangThai'  => 'Trạng thái',
            'NgayNopDon' => 'Ngày nộp đơn',
            'NgayDuyet'  => 'Ngày duyệt',
        ],
    ],
    'leave-balances' => [
        'title' => 'Quỹ phép năm',
        'subtitle' => 'Quản trị số dư phép năm theo từng nhân viên',
        'service' => 'hr',
        'resource' => 'leave-balances',
        'legacy_prefix' => 'quyphep',
        'legacy_name' => 'quyphep',
        'permission' => [
            'view' => 'xem_quyphep',
            'create' => 'them_quyphep',
            'update' => 'sua_quyphep',
            'delete' => 'xoa_quyphep',
        ],
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien', 'value_col' => 'MaNV', 'label_col' => 'HoTen'],
        ],
        'hidden_columns' => ['created_at', 'updated_at'],
        'hidden_form_columns' => ['created_at', 'updated_at'],
        'field_labels' => [
            'id' => 'Mã quỹ phép',
            'MaNV' => 'Nhân viên',
            'Nam' => 'Năm',
            'EntitledDays' => 'Tổng ngày phép',
            'UsedDays' => 'Đã sử dụng',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Cập nhật lần cuối',
        ],
    ],
    'reward-records' => [
        'title' => 'Khen thưởng kỷ luật',
        'subtitle' => 'Quản trị các quyết định thưởng phạt trong hệ thống',
        'service' => 'hr',
        'resource' => 'reward-discipline-records',
        'legacy_prefix' => 'khenthuong',
        'legacy_name' => 'khenthuong',
        'permission' => ['view' => 'xem_khenthuong', 'create' => 'them_khenthuong', 'update' => 'sua_khenthuong', 'delete' => 'xoa_khenthuong'],
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien', 'value_col' => 'MaNV', 'label_col' => 'HoTen'],
            'MaLoai' => ['service' => 'hr', 'table' => 'loaikhenthuongkyluat', 'value_col' => 'MaLoai', 'label_col' => 'TenLoai'],
        ],
        'field_labels' => [
            'MaKTKL'        => 'Mã khen thưởng/kỷ luật',
            'MaNV'          => 'Nhân viên',
            'MaLoai'        => 'Loại',
            'NgayQuyetDinh' => 'Ngày quyết định',
            'HinhThuc'      => 'Hình thức',
            'SoTien'        => 'Số tiền',
            'LyDo'          => 'Lý do',
            'GhiChu'        => 'Ghi chú',
        ],
    ],
    'reward-types' => [
        'title' => 'Loại khen thưởng kỷ luật',
        'subtitle' => 'Quản trị danh mục loại thưởng phạt',
        'service' => 'hr',
        'resource' => 'reward-discipline-types',
        'legacy_prefix' => 'loaikhenthuong',
        'legacy_name' => 'loaikhenthuong',
        'permission' => ['view' => 'xem_khenthuong', 'create' => 'them_khenthuong', 'update' => 'sua_khenthuong', 'delete' => 'xoa_khenthuong'],
        'field_labels' => [
            'MaLoai'  => 'Mã loại',
            'TenLoai' => 'Tên loại',
            'Loai'    => 'Nhóm',
            'MoTa'    => 'Mô tả',
        ],
    ],
    'employee-profiles' => [
        'title' => 'Hồ sơ nhân viên',
        'subtitle' => 'Quản trị hồ sơ cá nhân trong hệ thống',
        'service' => 'hr',
        'resource' => 'employee-profiles',
        'legacy_prefix' => 'hosocanhan',
        'legacy_name' => 'hosocanhan',
        'permission' => ['view' => 'xem_nhanvien', 'create' => 'them_hoso', 'update' => 'sua_nhanvien', 'delete' => 'xoa_nhanvien'],
        'file_fields' => ['Anh'],
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien',  'value_col' => 'MaNV', 'label_col' => 'HoTen'],
            'MaPB' => ['service' => 'hr', 'table' => 'phongban',  'value_col' => 'MaPB', 'label_col' => 'TenPB'],
            'MaCV' => ['service' => 'hr', 'table' => 'chucvu',    'value_col' => 'MaCV', 'label_col' => 'TenCV'],
        ],
        'field_labels' => [
            'MaHoSo'          => 'Mã hồ sơ',
            'MaNV'            => 'Mã nhân viên',
            'CCCD'            => 'Số CCCD',
            'NoiCap'          => 'Nơi cấp',
            'NgayCap'         => 'Ngày cấp',
            'DiaChi'          => 'Địa chỉ',
            'DanToc'          => 'Dân tộc',
            'TonGiao'         => 'Tôn giáo',
            'TrinhDo'         => 'Trình độ học vấn',
            'ChuyenMon'       => 'Chuyên môn',
            'NgayVaoLam'      => 'Ngày vào làm',
            'MaPB'            => 'Phòng ban',
            'MaCV'            => 'Chức vụ',
            'TrangThaiHonNhan' => 'Tình trạng hôn nhân',
            'Anh'             => 'Ảnh đại diện',
        ],
    ],
    'contracts' => [
        'title' => 'Hợp đồng',
        'subtitle' => 'Quản trị hợp đồng lao động trong hệ thống',
        'service' => 'payroll',
        'resource' => 'contracts',
        'legacy_prefix' => 'hopdong',
        'legacy_name' => 'hopdong',
        'permission' => ['view' => 'xem_hopdong', 'create' => 'them_hopdong', 'update' => 'sua_hopdong', 'delete' => 'xoa_hopdong'],
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien', 'value_col' => 'MaNV', 'label_col' => 'HoTen'],
            'MaBac' => ['service' => 'payroll', 'table' => 'bacluong', 'value_col' => 'MaBac', 'label_col' => 'TenBac'],
        ],
        'field_options' => [
            'LoaiHopDong' => ['Thử việc', 'Xác định thời hạn', 'Không xác định thời hạn'],
            'TrangThai'   => ['Còn hiệu lực', 'Hết hiệu lực'],
        ],
        'field_labels' => [
            'MaHopDong'     => 'Mã hợp đồng',
            'HopDongGoc'    => 'Hợp đồng gốc',
            'SoHopDong'     => 'Số hợp đồng',
            'MaNV'          => 'Nhân viên',
            'MaBac'         => 'Bậc lương',
            'LoaiHopDong'   => 'Loại hợp đồng',
            'NgayBatDau'    => 'Ngày bắt đầu',
            'NgayKetThuc'   => 'Ngày kết thúc',
            'GhiChu'        => 'Ghi chú',
            'LoaiCong'      => 'Loại công',
            'NgayKy'        => 'Ngày ký',
            'TrangThai'     => 'Trạng thái',
        ],
    ],
    'salary-bands' => [
        'title' => 'Ngạch lương',
        'subtitle' => 'Quản trị hệ thống ngạch lương',
        'service' => 'payroll',
        'resource' => 'salary-bands',
        'legacy_prefix' => 'ngachluong',
        'legacy_name' => 'ngachluong',
        'permission' => ['view' => 'xem_ngachluong', 'create' => 'xem_ngachluong', 'update' => 'xem_ngachluong', 'delete' => 'xem_ngachluong'],
        'read_only' => true,
        'disable_filter' => true,
        'disable_export' => true,
        'hidden_columns' => ['TrangThai'],
        'hide_actions' => true,
        'field_labels' => [
            'MaNgach' => 'Mã ngạch',
            'TenNgach' => 'Tên ngạch',
            'MoTa' => 'Mô tả',
        ],
    ],
    'salary-grades' => [
        'title' => 'Bậc lương',
        'subtitle' => 'Quản trị các bậc lương trong hệ thống',
        'service' => 'payroll',
        'resource' => 'salary-grades',
        'legacy_prefix' => 'bacluong',
        'legacy_name' => 'bacluong',
        'permission' => ['view' => 'xem_bacluong', 'create' => 'xem_bacluong', 'update' => 'xem_bacluong', 'delete' => 'xem_bacluong'],
        'read_only' => true,
        'disable_filter' => true,
        'disable_export' => true,
        'hidden_columns' => ['TrangThai'],
        'hide_actions' => true,
        'field_labels' => [
            'MaBac' => 'Mã bậc',
            'MaNgach' => 'Mã ngạch',
            'TenBac' => 'Tên bậc',
            'HeSoLuong' => 'Hệ số lương',
            'LuongCoSo' => 'Lương cơ sở',
            'PhuCap' => 'Phụ cấp',
            'MoTa' => 'Mô tả',
        ],
    ],
    'accounts' => [
        'title' => 'Tài khoản',
        'subtitle' => 'Quản trị tài khoản đăng nhập và thông tin truy cập',
        'service' => 'hr',
        'resource' => 'accounts',
        'legacy_prefix' => 'taikhoan',
        'legacy_name' => 'taikhoan',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'them_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'xoa_taikhoan'],
        'field_lookups' => [
            'MaNV' => ['service' => 'hr', 'table' => 'nhanvien', 'value_col' => 'MaNV', 'label_col' => 'HoTen'],
            'MaNVRef' => ['service' => 'hr', 'table' => 'nhanvien', 'value_col' => 'MaNV', 'label_col' => 'HoTen'],
        ],
        'field_options' => [
            'TrangThai' => ['Hoạt động', 'Khóa'],
        ],
        'field_labels' => [
            'MaTK'              => 'Mã tài khoản',
            'TenDangNhap'       => 'Tên đăng nhập',
            'MatKhau'           => 'Mật khẩu',
            'MaNV'              => 'Nhân viên',
            'MaNVRef'           => 'Nhân viên tham chiếu',
            'TrangThai'         => 'Trạng thái',
            'BuocDoiMatKhau'    => 'Bước đổi mật khẩu',
            'NgayCapMatKhauTam' => 'Ngày cấp mật khẩu tạm',
            'NgayTao'           => 'Ngày tạo',
        ],
    ],
    'roles' => [
        'title' => 'Vai trò',
        'subtitle' => 'Quản trị vai trò hệ thống',
        'service' => 'hr',
        'resource' => 'roles',
        'legacy_prefix' => 'vaitro',
        'legacy_name' => 'vaitro',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'sua_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'sua_taikhoan'],
    ],
    'features' => [
        'title' => 'Chức năng',
        'subtitle' => 'Quản trị danh mục quyền/chức năng hệ thống',
        'service' => 'hr',
        'resource' => 'features',
        'legacy_prefix' => 'chucnang',
        'legacy_name' => 'chucnang',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'sua_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'sua_taikhoan'],
    ],
    'account-roles' => [
        'title' => 'Gán vai trò tài khoản',
        'subtitle' => 'Quản trị vai trò của từng tài khoản',
        'service' => 'hr',
        'resource' => 'account-roles',
        'legacy_prefix' => 'gantaikhoanvaitro',
        'legacy_name' => 'gantaikhoanvaitro',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'sua_taikhoan', 'update' => 'sua_taikhoan', 'delete' => 'sua_taikhoan'],
    ],
    'audit-logs' => [
        'title' => 'Nhật ký hệ thống',
        'subtitle' => 'Theo dõi phiên đăng nhập và lịch sử truy vết',
        'service' => 'hr',
        'resource' => 'session-audits',
        'legacy_prefix' => 'auditlog',
        'legacy_name' => 'auditlog',
        'permission' => ['view' => 'xem_taikhoan', 'create' => 'xem_taikhoan', 'update' => 'xem_taikhoan', 'delete' => 'xem_taikhoan'],
        'read_only' => true,
        'field_labels' => [
            'id' => 'ID',
            'MaTK' => 'Mã tài khoản',
            'session_marker' => 'Mã phiên',
            'user_agent' => 'Trình duyệt',
            'ip_address' => 'Địa chỉ IP',
            'created_at' => 'Thời điểm tạo',
            'last_activity' => 'Hoạt động cuối',
            'revoked_at' => 'Thời điểm thu hồi',
        ],
    ],
];